### PR TITLE
Update for CM13

### PR DESCRIPTION
**Pull request by mimi89999**
@mar-v-in

### CODE REVIEW

**Comment by mimi89999** [comment]
@mar-v-in PsychoI3oy said, that LockClock doesn't include proprietary code......
https://github.com/CyanogenMod/android_packages_apps_LockClock/commit/c5a4398fae1116f0db5a6fe2b3a36fb74c4b723d#commitcomment-17181432

**Comment by Mystro256** [comment]
Though that is true, @mar-v-in has clarified before that the purpose of freecyngn is to remove all non driver related code that contains, or links to, nonfree code.

**Comment by mimi89999** [comment]
AFAIK it imports the GMS lib (`import com.google.android.gms`)

**Comment by Mystro256** [comment]
AFAIK, importing is the equivalent to linking in Java. Isn't GMS lib proprietary?
A better question could be, is his compatible with linking to microg instead? If so, should this actually be removed?

**Comment by mimi89999** [comment]
GMS lib is non-free and that's my point...

**Pull request merged**
